# Generated by Django 2.0.7 on 2018-07-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_auto_20180719_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Início')),
                ('end', models.DateTimeField(verbose_name='Fim')),
                ('duration', models.DurationField(verbose_name='Duração')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
        ),
    ]
