# Generated by Django 2.0.7 on 2018-07-19 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='function',
            new_name='role',
        ),
    ]
