# Generated by Django 2.0.7 on 2018-07-19 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_event_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projetos.Project', verbose_name='Projeto'),
            preserve_default=False,
        ),
    ]
