# Generated by Django 2.0.7 on 2018-07-19 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0007_participant_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projetos.Participant', verbose_name='Participante'),
            preserve_default=False,
        ),
    ]
