# Generated by Django 2.0.7 on 2018-07-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0009_auto_20180719_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Função'),
        ),
    ]
