# Generated by Django 2.0.7 on 2018-07-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0010_auto_20180720_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(default=None, max_length=255, verbose_name='Função'),
            preserve_default=False,
        ),
    ]
