# Generated by Django 2.0.7 on 2018-07-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0011_auto_20180720_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Projeto'},
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='project',
            name='time_value',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor da hora'),
        ),
    ]
